export const LightThemeImages = {
  emailIcon: require('../assets/images/email-icon-white.png'),
  userIcon : require('../assets/images/userprofile-icon-outline-gray.png'),
  eyeIcon: require('../assets/images/eye-icon-white.png'),
  keyIcon: require('../assets/images/key-icon-white.png'),
  checkIcon: require('../assets/images/check-icon-gray.png'),
  threeDotsIcon: require('../assets/images/three-dots-icon.png'),
  starIconGold: require('../assets/images/star-icon-gold.png'),
  starIconGray: require('../assets/images/star-icon-gray.png'),
  numConGradBlue: require('../assets/images/num-container-gradient-blue.png'),
  magnifierIconGray: require('../assets/images/magnifier-icon-gray.png'),
  magnifierIconWhite: require('../assets/images/magnifier-icon-white.png'),
  osIconWhite: require('../assets/images/fellows-os-logo.png'),
  lampIconWhite: require('../assets/images/lamp-icon-white.png'),
  vpnIconWhite: require('../assets/images/vpn-lock-icon-white.png'),
  bookPageIconWhite: require('../assets/images/book-page-icon-white.png'),
  commentIconWhite: require('../assets/images/comment-icon-white.png'),
  bellIconWhite: require('../assets/images/bell-icon-white.png'),
  chevronDownWhite: require('../assets/images/chevron-down-white.png'),
  mockProfileImage: require('../assets/images/mock-profile.png'),
  navMenuWhite: require('../assets/images/nav-menu-icon-white.png'),
  chevronDownGray: require('../assets/images/chevron-down-gray.png'),
  imageGenericIconGray: require('../assets/images/image-generic-icon-gray.png'),
  newTextWhite: require('../assets/images/new-text-white.png'),
  historyIconRed: require('../assets/images/history-icon-red.png'),
  shareIconWhite: require('../assets/images/share-icon-white.png'),
  waveIconWhite: require('../assets/images/wave-icon-white.png'),
  letterLIconGray: require('../assets/images/L-gray.png'),
  letterLIconWhite: require('../assets/images/L-white.png'),
  letterCIconGray: require('../assets/images/C-gray.png'),
  letterCIconWhite: require('../assets/images/C-white.png'),
  smileyIconGray: require('../assets/images/smiley-icon-gray.png'),
  cameraIconGray: require('../assets/images/camera-icon-gray.png'),
  gifIconGray: require('../assets/images/gif-icon-gray.png'),
  saveOutlineIconGray: require('../assets/images/save-outline-icon-gray.png'),
  sendIconSolid: require('../assets/images/send-solid-gray.png'),
  newspaperIconSolid: require('../assets/images/newspaper-solid-gray.png'),
  mailIconSolid: require('../assets/images/mail-solid-gray.png'),
  fbIconSolid: require('../assets/images/fb-solid-gray.png'),
  twitterIconSolid: require('../assets/images/twitter-solid-gray.png'),
  linkedinIconSolid: require('../assets/images/linkedin-solid-gray.png'),
  curvedTriangleWhite: require('../assets/images/curved-triangle-white.png'),
  pencilSolidGray: require('../assets/images/pencil-solid-gray.png'),
  bellSolidGray: require('../assets/images/bell-solid-gray.png'),
  warningSolidGray: require('../assets/images/warning-solid-gray.png'),
  snoozeSolidGray: require('../assets/images/snooze-solid-gray.png'),
  unfollowSolidGray: require('../assets/images/unfollow-solid-gray.png'),
  cooldownSolidGray: require('../assets/images/cooldown-solid-gray.png'),
  xIconGray: require('../assets/images/x-icon-gray.png'),
  gripeZoneImage : require('../assets/images/lime-bad-news-from-newspaper.png'),
  bellSolidSlashedGray : require('../assets/images/bell-solid-slashed-gray.png'),
  bellOutlineSlashedGray : require('../assets/images/bell-outline-slashed-gray.png'),
  cloudUploadIconBig : require('../assets/images/cloud-upload-big-icon.png'),
  homeIconOutline :require("../assets/images/addresshome.png"),
  locationIconOutline :require("../assets/images/location-icon-outline-gray.png"),
  linkIconOutline:require("../assets/images/position.png"),
  childBirthIconOutline:require("../assets/images/child.png"),
  bookPageIconOutline:require("../assets/images/education.png"),
  trophyIconOultine:require("../assets/images/praid.png"),
  userProfileIconOutline :require("../assets/images/userprofile-icon-outline-gray.png"),
  genericImageIconOutline :require("../assets/images/image-02.png"),
}

export const DarkThemeImages = {
  ...LightThemeImages
}
